{
  "formatVersion": "1.1",
  "component": {
    "group": "com.changyow.ems",
    "module": "ems-otg-lib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "ems-otg-lib-1.0.0.aar",
          "url": "ems-otg-lib-1.0.0.aar",
          "size": 38969,
          "sha512": "a669a70ba93ed4f2900f3e346cc46c421c280e359121fb09058cfa35aef9a71aa57902cfead3cf74c1d5280d408e5c932b533ca03e4fb2c2b0a05748769de34c",
          "sha256": "4c760afc5acff37433ea5ab3bc79fc0d452eb2db3409d082ae210e1f78324bbf",
          "sha1": "bfb6a2d5360f923d4b9a1adb73471ca41b6d5e39",
          "md5": "e57402612bef9bb8f6a6f0b749ce15fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "ems-otg-lib-1.0.0.aar",
          "url": "ems-otg-lib-1.0.0.aar",
          "size": 38969,
          "sha512": "a669a70ba93ed4f2900f3e346cc46c421c280e359121fb09058cfa35aef9a71aa57902cfead3cf74c1d5280d408e5c932b533ca03e4fb2c2b0a05748769de34c",
          "sha256": "4c760afc5acff37433ea5ab3bc79fc0d452eb2db3409d082ae210e1f78324bbf",
          "sha1": "bfb6a2d5360f923d4b9a1adb73471ca41b6d5e39",
          "md5": "e57402612bef9bb8f6a6f0b749ce15fc"
        }
      ]
    }
  ]
}
